[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# Railway supports multiple containers per service
# Monitoring services will be deployed alongside the main API

# Multi-service deployment configuration
[services.api]
build = { builder = "dockerfile", dockerfilePath = "Dockerfile" }
healthcheckPath = "/health"

[services.prometheus]
build = { builder = "dockerfile", dockerfilePath = "Dockerfile.monitoring" }
healthcheckPath = "/-/healthy"
sourceDir = "monitoring/prometheus"

[services.grafana]
build = { builder = "dockerfile", dockerfilePath = "Dockerfile.monitoring" }
healthcheckPath = "/api/health"
sourceDir = "monitoring/grafana"

[services.loki]
build = { builder = "dockerfile", dockerfilePath = "Dockerfile.monitoring" }
healthcheckPath = "/ready"
sourceDir = "monitoring/loki"

[services.promtail]
build = { builder = "dockerfile", dockerfilePath = "Dockerfile.monitoring" }
sourceDir = "monitoring/promtail"

[environments.production]
DATABASE_URL = "${{ RAILWAY_PROJECT_ENV.DATABASE_URL }}"
REDIS_URL = "${{ RAILWAY_PROJECT_ENV.REDIS_URL }}"
RABBITMQ_URL = "${{ RAILWAY_PROJECT_ENV.RABBITMQ_URL }}"

# JWT Configuration
JWT_SECRET_KEY = "${{ secrets.JWT_SECRET_KEY }}"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_DAYS = "7"

# Email Configuration (Mailjet)
MAILJET_API_KEY = "${{ secrets.MAILJET_API_KEY }}"
MAILJET_API_SECRET = "${{ secrets.MAILJET_API_SECRET }}"
FROM_EMAIL = "${{ secrets.FROM_EMAIL }}"
FROM_NAME = "${{ secrets.FROM_NAME }}"
FRONTEND_URL = "${{ secrets.FRONTEND_URL }}"

# Application Configuration
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
SERVICE_NAME = "donations-api"
VERSION = "1.0.0"

# CORS Configuration
ALLOWED_ORIGINS = "${{ secrets.ALLOWED_ORIGINS }}"

# Rate Limiting
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# Monitoring
GRAFANA_ADMIN_USER = "${{ secrets.GRAFANA_ADMIN_USER }}"
GRAFANA_ADMIN_PASSWORD = "${{ secrets.GRAFANA_ADMIN_PASSWORD }}"