[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
DATABASE_URL = "${{ RAILWAY_PROJECT_ENV.DATABASE_URL }}"
REDIS_URL = "${{ RAILWAY_PROJECT_ENV.REDIS_URL }}"
RABBITMQ_URL = "${{ RAILWAY_PROJECT_ENV.RABBITMQ_URL }}"

# JWT Configuration
JWT_SECRET_KEY = "${{ secrets.JWT_SECRET_KEY }}"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_DAYS = "7"

# Email Configuration
SMTP_SERVER = "${{ secrets.SMTP_SERVER }}"
SMTP_PORT = "${{ secrets.SMTP_PORT }}"
SMTP_USERNAME = "${{ secrets.SMTP_USERNAME }}"
SMTP_PASSWORD = "${{ secrets.SMTP_PASSWORD }}"
FROM_EMAIL = "${{ secrets.FROM_EMAIL }}"
FRONTEND_URL = "${{ secrets.FRONTEND_URL }}"

# Application Configuration
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

# Rate Limiting
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# Monitoring
GRAFANA_ADMIN_USER = "${{ secrets.GRAFANA_ADMIN_USER }}"
GRAFANA_ADMIN_PASSWORD = "${{ secrets.GRAFANA_ADMIN_PASSWORD }}"