global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Donations API
  - job_name: 'donations-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    # Custom labels for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'donations-api'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'development'

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # RabbitMQ metrics
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics (if running)
  # Remove the comment below to enable node-exporter when deployed
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 30s

  # Custom business metrics (example)
  - job_name: 'donations-business'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics/business'
    scrape_interval: 60s  # Less frequent for business metrics