"""Add comprehensive indexes and constraints for performance and data integrity

Revision ID: 04af93108f49
Revises: 47c7306d848e
Create Date: 2025-09-02 01:15:53.521765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04af93108f49'
down_revision = '47c7306d848e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('donations_correlation_id_key', 'donations', type_='unique')
    op.drop_constraint('donations_reference_code_key', 'donations', type_='unique')
    op.create_index(op.f('ix_donations_amount_gtq'), 'donations', ['amount_gtq'], unique=False)
    op.create_index(op.f('ix_donations_correlation_id'), 'donations', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_donor_email'), 'donations', ['donor_email'], unique=False)
    op.create_index(op.f('ix_donations_reference_code'), 'donations', ['reference_code'], unique=True)
    op.drop_constraint('email_logs_provider_msg_id_key', 'email_logs', type_='unique')
    op.create_index(op.f('ix_email_logs_attempt'), 'email_logs', ['attempt'], unique=False)
    op.create_index(op.f('ix_email_logs_donation_id'), 'email_logs', ['donation_id'], unique=False)
    op.create_index(op.f('ix_email_logs_provider_msg_id'), 'email_logs', ['provider_msg_id'], unique=True)
    op.create_index(op.f('ix_email_logs_sent_at'), 'email_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_logs_status_id'), 'email_logs', ['status_id'], unique=False)
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    # Skipping payload_raw type change due to view dependencies
    # op.alter_column('payment_events', 'payload_raw',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_payment_events_donation_id'), 'payment_events', ['donation_id'], unique=False)
    op.create_index(op.f('ix_payment_events_received_at'), 'payment_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_payment_events_signature_ok'), 'payment_events', ['signature_ok'], unique=False)
    op.create_index(op.f('ix_payment_events_status_id'), 'payment_events', ['status_id'], unique=False)
    # Skipping identity column modification due to existing identity column
    # op.alter_column('roles', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.text('identity()'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping identity column modification due to existing identity column
    # op.alter_column('roles', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_payment_events_status_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_signature_ok'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_received_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_donation_id'), table_name='payment_events')
    # Skipping payload_raw type change due to view dependencies
    # op.alter_column('payment_events', 'payload_raw',
    #            existing_type=sa.JSON(),
    #            type_=postgresql.JSONB(astext_type=sa.Text()),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_status_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_sent_at'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_provider_msg_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_donation_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_attempt'), table_name='email_logs')
    op.create_unique_constraint('email_logs_provider_msg_id_key', 'email_logs', ['provider_msg_id'])
    op.drop_index(op.f('ix_donations_reference_code'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_email'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_index(op.f('ix_donations_correlation_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_amount_gtq'), table_name='donations')
    op.create_unique_constraint('donations_reference_code_key', 'donations', ['reference_code'])
    op.create_unique_constraint('donations_correlation_id_key', 'donations', ['correlation_id'])
    # ### end Alembic commands ###