"""Add simple_users table for CRUD POC

Revision ID: 3acc0fa3037e
Revises: a641193ddb9b
Create Date: 2025-09-26 16:11:14.059036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acc0fa3037e'
down_revision = 'a641193ddb9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_users_email'), 'simple_users', ['email'], unique=True)
    op.create_index(op.f('ix_simple_users_id'), 'simple_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_users_id'), table_name='simple_users')
    op.drop_index(op.f('ix_simple_users_email'), table_name='simple_users')
    op.drop_table('simple_users')
    # ### end Alembic commands ###